[project]
name = "quarto-analysis"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "arviz>=0.22.0",
    "bambi>=0.16.0",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.7",
    "numpy>=2.3.5",
    "pandas>=2.3.3",
    "pymc>=5.26.1",
    "radian>=0.6.15",
]
